//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssentUniqueNumber
    {
        public int AssentUniqueNumber1 { get; set; }
        public Nullable<int> Number { get; set; }
        public string Year { get; set; }
        public Nullable<int> ClientAssetID { get; set; }
    
        public virtual ClientAsset ClientAsset { get; set; }
    }
}
