//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentFile
    {
        public int AttachFileID { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> FileID { get; set; }
        public string FileName { get; set; }
        public string FileExtention { get; set; }
        public Nullable<int> FileSize { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> ReferenceFileid { get; set; }
    }
}
