//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_ClientFocalPoint_View
    {
        public int ClientFocalPointID { get; set; }
        public string ClientFocalPointCode { get; set; }
        public string ClientFocalPointName { get; set; }
        public int ClientID { get; set; }
        public string Clientname { get; set; }
    }
}
