//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class commentedAttachFile
    {
        public int commentedAttachFileId { get; set; }
        public int FileID { get; set; }
        public string AttachFilePath { get; set; }
        public string UserID { get; set; }
        public System.DateTime Createdon { get; set; }
    }
}
