//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Confidential
    {
        public int ConfidentialID { get; set; }
        public Nullable<int> MilestoneID { get; set; }
        public Nullable<int> RevisionID { get; set; }
        public Nullable<int> DeliverableID { get; set; }
    }
}
