//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractNormColMaster
    {
        public int ContractNormsColumnID { get; set; }
        public string IsDbField { get; set; }
        public string DisplayColName { get; set; }
        public string DBColName { get; set; }
        public Nullable<int> DBFKID { get; set; }
        public string TableName { get; set; }
        public int DisplayOrder { get; set; }
        public string DataType { get; set; }
        public string InputOutput { get; set; }
        public string EquationID { get; set; }
        public string DisplayInGrid { get; set; }
        public string IsDropDown { get; set; }
        public string NameInDb { get; set; }
        public string IsMandatory { get; set; }
        public string IsPkField { get; set; }
        public string IsSearchField { get; set; }
        public Nullable<int> DBColPkID { get; set; }
        public string IsContractMapping { get; set; }
        public int ContractNormSetID { get; set; }
        public int CompanyNormSetID { get; set; }
    }
}
