//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomReportFilterMaster
    {
        public int CustomReportFilterID { get; set; }
        public Nullable<int> CustomReportID { get; set; }
        public string TableName { get; set; }
        public string CoulumnValue { get; set; }
        public string ReportTitle { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
