//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverableMessage
    {
        public int DeliverableMessageID { get; set; }
        public string Message { get; set; }
        public string RecipentID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> Uploaddeliberablefileid { get; set; }
        public Nullable<bool> CheckRead { get; set; }
        public Nullable<int> DeliverableID { get; set; }
    }
}
