//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        //public Designation()
        //{
        //    this.Users = new HashSet<User>();
        //}
        [Key]
        public int DesignationID { get; set; }
        public string DesignationName { get; set; }
        public string DesignationCode { get; set; }
        //public string DistributationReq { get; set; }
        //public Nullable<int> DisplayOrder { get; set; }
    
       
    }
}
