//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentFilter
    {
        public DocumentFilter()
        {
            this.IndividualRecipients = new HashSet<IndividualRecipient>();
        }
    
        public int DocumentFiltersID { get; set; }
        public Nullable<int> TaskTypeID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public Nullable<int> MilestoneID { get; set; }
        public Nullable<int> RevisionID { get; set; }
        public bool CanComment { get; set; }
        public int ProjectID { get; set; }
    
        public virtual ICollection<IndividualRecipient> IndividualRecipients { get; set; }
    }
}
