//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplate
    {
        public decimal EmailTemplateID { get; set; }
        public string EmailTemplateDesc { get; set; }
        public string EmailTemplateSubject { get; set; }
        public string EmailTemplateMessage { get; set; }
        public string SMSTemplateMessage { get; set; }
        public string Status { get; set; }
        public string ProgramTypes { get; set; }
        public string GroupingOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string DisplayInGrid { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
