//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimationColSettingTemplate
    {
        public EstimationColSettingTemplate()
        {
            this.EstimationColSettingTemplateDetails = new HashSet<EstimationColSettingTemplateDetail>();
        }
    
        public int EstimationColSettingTemplateID { get; set; }
        public string EstimationColSettingTemplateName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string DefaultTemplate { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> MasterTaskTypeID { get; set; }
    
        public virtual ICollection<EstimationColSettingTemplateDetail> EstimationColSettingTemplateDetails { get; set; }
    }
}
