//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExUser
    {
        public int ExUserID { get; set; }
        public string ExUser1 { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Name { get; set; }
        public string CompanyName { get; set; }
        public string PhoneNo { get; set; }
        public string Designation { get; set; }
        public string Role { get; set; }
        public string Location { get; set; }
        public Nullable<int> ContactTypeID { get; set; }
    }
}
