//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileChecker
    {
        public int FileCheckerID { get; set; }
        public Nullable<int> UploadDeliverableFileID { get; set; }
        public string UserID { get; set; }
        public string flag { get; set; }
        public string CanEdit { get; set; }
        public string IsClient { get; set; }
        public string IsTransmittal { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string MessageID { get; set; }
        public string MessageBody { get; set; }
        public string MessageSubject { get; set; }
        public string SenderId { get; set; }
        public Nullable<int> SentCounter { get; set; }
    
        public virtual UploadDeliverableFile UploadDeliverableFile { get; set; }
    }
}
