//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileStatu
    {
        public int FileStatusID { get; set; }
        public Nullable<int> FileID { get; set; }
        public Nullable<int> ProgresslevelID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> PreviousStatusID { get; set; }
    }
}
