//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class GanntChartSetting
    {
        public int GanttSettingID { get; set; }
        public bool IsOpenEnded { get; set; }
        public bool IsAdjustForecast { get; set; }
        public bool IsDispalyProgress { get; set; }
        public string CriticalActivity { get; set; }
        public int FloatValue { get; set; }
        public int UserID { get; set; }
        public bool IsHighlightCrtPath { get; set; }
        public string IsSegregate { get; set; }
    }
}
