//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialdetailsColumn
    {
        public int MaterialdetailsColID { get; set; }
        public Nullable<int> EstimationTaskColumnID { get; set; }
        public Nullable<int> MilestoneID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Type { get; set; }
        public string OwnerRights { get; set; }
        public string RecipientRights { get; set; }
        public string ProjectAdminRights { get; set; }
    }
}
