//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialUnit
    {
        public MaterialUnit()
        {
            this.MaterialNorms = new HashSet<MaterialNorm>();
        }
    
        public int UnitID { get; set; }
        public string UnitName { get; set; }
        public string UnitCode { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual ICollection<MaterialNorm> MaterialNorms { get; set; }
    }
}
