//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialInventory
    {
        public int MaterialInventoryID { get; set; }
        public Nullable<int> FromStoreID { get; set; }
        public Nullable<int> TranTypeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ReceiveBy { get; set; }
        public string VehicleNo { get; set; }
        public string Driver { get; set; }
        public Nullable<int> PurcaseOrder { get; set; }
        public Nullable<int> ToStore { get; set; }
        public string Remarks { get; set; }
        public string TranType { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<double> Number_1 { get; set; }
        public Nullable<double> Number_2 { get; set; }
        public Nullable<double> Number_3 { get; set; }
        public Nullable<double> Number_4 { get; set; }
        public Nullable<double> Number_5 { get; set; }
        public Nullable<double> Number_6 { get; set; }
        public Nullable<double> Number_7 { get; set; }
        public Nullable<double> Number_8 { get; set; }
        public Nullable<double> Number_9 { get; set; }
        public Nullable<double> Number_10 { get; set; }
        public Nullable<System.DateTime> DateTime_1 { get; set; }
        public Nullable<System.DateTime> DateTime_2 { get; set; }
        public Nullable<System.DateTime> DateTime_3 { get; set; }
        public Nullable<System.DateTime> DateTime_4 { get; set; }
        public Nullable<System.DateTime> DateTime_5 { get; set; }
        public Nullable<System.DateTime> DateTime_6 { get; set; }
        public Nullable<System.DateTime> DateTime_7 { get; set; }
        public Nullable<System.DateTime> DateTime_8 { get; set; }
        public Nullable<System.DateTime> DateTime_9 { get; set; }
        public Nullable<System.DateTime> DateTime_10 { get; set; }
        public string String_1 { get; set; }
        public string String_2 { get; set; }
        public string String_3 { get; set; }
        public string String_4 { get; set; }
        public string String_5 { get; set; }
        public string String_6 { get; set; }
        public string String_7 { get; set; }
        public string String_8 { get; set; }
        public string String_9 { get; set; }
        public string String_10 { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    }
}
