//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialNorm
    {
        public int MaterialNormsID { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string Capacity { get; set; }
        public string Make { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> SrNo { get; set; }
        public string UnitPriceJS { get; set; }
        public string Code { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual MaterialUnit MaterialUnit { get; set; }
    }
}
