//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public string FromUserID { get; set; }
        public string ToUserID { get; set; }
        public string Message1 { get; set; }
        public string RedirectURL { get; set; }
        public string QueryString { get; set; }
        public string MessageFor { get; set; }
        public string Active { get; set; }
        public string MessageType { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string IsProgressAlert { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
