//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message_Temp
    {
        public int MessageID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public int FromUserID { get; set; }
        public int ToUserID { get; set; }
        public string Message { get; set; }
        public string RedirectURL { get; set; }
        public string QueryString { get; set; }
        public string MessageFor { get; set; }
        public string Active { get; set; }
        public string MessageType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
    }
}
