//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilestonesStakeHolder
    {
        public int MilestonesStakeHoldersID { get; set; }
        public int ProjectID { get; set; }
        public string UserID { get; set; }
        public int MilestoneID { get; set; }
        public int RevisionID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string Flag { get; set; }
    }
}
