//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewActivity
    {
        public NewActivity()
        {
            this.NewActivityDetails = new HashSet<NewActivityDetail>();
        }
    
        public int NewActivityID { get; set; }
        public string ActivityName { get; set; }
        public string ActivityNo { get; set; }
        public string Billable { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<decimal> MaxHours { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    
        public virtual ICollection<NewActivityDetail> NewActivityDetails { get; set; }
    }
}
