//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NextStepMessageUser
    {
        public int NextStepMessagesUserID { get; set; }
        public Nullable<int> NextStepMessagesID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> Disable { get; set; }
    }
}
