//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NextStepMessage
    {
        public int NextStepMessagesID { get; set; }
        public string RoleType { get; set; }
        public string ActionLocation { get; set; }
        public string MessageType { get; set; }
        public string PopupLocation { get; set; }
        public string MessageText { get; set; }
        public string Page { get; set; }
    }
}
