//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormsManageTableColumn
    {
        public int NormsManageTableColId { get; set; }
        public int NormsManageTableID { get; set; }
        public string NormsManageTableColName { get; set; }
        public string NormsManageMasterTable { get; set; }
        public string NormsManageMasterTableColumn { get; set; }
    }
}
