//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormSet
    {
        public int NormSetID { get; set; }
        public string NormSetName { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public Nullable<int> ProjectStage { get; set; }
        public string NormSetType { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string IsDefault { get; set; }
    }
}
