//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormsMapping
    {
        public int NormsMappingID { get; set; }
        public int CompanyNormID { get; set; }
        public int CompanyNormSetID { get; set; }
        public int ContractNormID { get; set; }
        public int ContractNormSetID { get; set; }
    }
}
