//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Norm
    {
        public int NormsID { get; set; }
        public string NormsName { get; set; }
        public int NormType { get; set; }
        public string IsDeleted { get; set; }
        public int NormSetID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> ProjectStage { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
