//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageCommentDetail
    {
        public int PageCommentDetailID { get; set; }
        public Nullable<int> PageDetailID { get; set; }
        public Nullable<int> CenterX { get; set; }
        public Nullable<int> CenterY { get; set; }
        public string Text { get; set; }
        public Nullable<int> UploadDeliverableFileID { get; set; }
        public string CommentedBy { get; set; }
        public Nullable<int> ResponseBy { get; set; }
        public string Response { get; set; }
        public Nullable<int> CommentStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string Mergerow { get; set; }
        public Nullable<int> PageNo { get; set; }
        public Nullable<int> NumberOfPages { get; set; }
        public string ReasonForReject { get; set; }
        public string Item { get; set; }
        public Nullable<System.DateTime> CommentStatusDate { get; set; }
        public long CommentClientid { get; set; }
        public bool IsSent { get; set; }
    
        public virtual PageDetail PageDetail { get; set; }
        public virtual UploadDeliverableFile UploadDeliverableFile { get; set; }
    }
}
