//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageDetail
    {
        public PageDetail()
        {
            this.PageCircleDetails = new HashSet<PageCircleDetail>();
            this.PageClouds = new HashSet<PageCloud>();
            this.PageLineDetails = new HashSet<PageLineDetail>();
            this.PageRecDetails = new HashSet<PageRecDetail>();
            this.PageTextDetails = new HashSet<PageTextDetail>();
            this.PageCommentDetails = new HashSet<PageCommentDetail>();
        }
    
        public int PageDetailID { get; set; }
        public int FileID { get; set; }
        public Nullable<int> PageHeight { get; set; }
        public Nullable<int> PageWidth { get; set; }
        public Nullable<int> PageIndex { get; set; }
        public Nullable<int> TotalPageNumber { get; set; }
    
        public virtual ICollection<PageCircleDetail> PageCircleDetails { get; set; }
        public virtual ICollection<PageCloud> PageClouds { get; set; }
        public virtual ICollection<PageLineDetail> PageLineDetails { get; set; }
        public virtual ICollection<PageRecDetail> PageRecDetails { get; set; }
        public virtual ICollection<PageTextDetail> PageTextDetails { get; set; }
        public virtual ICollection<PageCommentDetail> PageCommentDetails { get; set; }
        public virtual UploadDeliverableFile UploadDeliverableFile { get; set; }
    }
}
