//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageCloudDetail
    {
        public int PageCloudDetailID { get; set; }
        public int PageCloudID { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
    
        public virtual PageCloud PageCloud { get; set; }
    }
}
