//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressUpdateNotificationSetting
    {
        public int NotificationID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> TaskTypeID { get; set; }
        public Nullable<int> RepeatEvery { get; set; }
        public Nullable<int> RepeatDate { get; set; }
        public string RepeatDay { get; set; }
        public string RepeatTime { get; set; }
        public Nullable<int> MilestoneID { get; set; }
    }
}
