//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressLevelNotification
    {
        public int ProgresslevelNotificationId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> ProjectMilestonesDocID { get; set; }
        public string RoleType { get; set; }
    
        public virtual ProjectMilestonesDocDetail ProjectMilestonesDocDetail { get; set; }
    }
}
