//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressLevelTemplateDocDetail
    {
        public int ProgressLevelTemplateStageDetailID { get; set; }
        public Nullable<int> ProgressLevelTemplateDetailID { get; set; }
        public Nullable<int> DocStageID { get; set; }
        public Nullable<decimal> DocStagePercentage { get; set; }
        public Nullable<int> TaskTypeID { get; set; }
    
        public virtual ProgressLevelTemplateDetail ProgressLevelTemplateDetail { get; set; }
    }
}
