//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressLevelTemplateDetail
    {
        public ProgressLevelTemplateDetail()
        {
            this.ProgressLevelTemplateDocDetails = new HashSet<ProgressLevelTemplateDocDetail>();
            this.ProjectProgressLevelTemplateTaskTypes = new HashSet<ProjectProgressLevelTemplateTaskType>();
        }
    
        public int ProgressLevelTemplateDetailID { get; set; }
        public Nullable<int> ProgressLevelTemplateID { get; set; }
        public string ProjectMilestone { get; set; }
        public string ProjectMilestoneDesc { get; set; }
        public Nullable<decimal> Weightage { get; set; }
        public string Type { get; set; }
        public string Remarks { get; set; }
        public string AutoDisplay { get; set; }
    
        public virtual ICollection<ProgressLevelTemplateDocDetail> ProgressLevelTemplateDocDetails { get; set; }
        public virtual ICollection<ProjectProgressLevelTemplateTaskType> ProjectProgressLevelTemplateTaskTypes { get; set; }
        public virtual ProjectProgressLevelTemplate ProjectProgressLevelTemplate { get; set; }
    }
}
