//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMilestonesDocDetail
    {
        public ProjectMilestonesDocDetail()
        {
            this.ProgressLevelNotifications = new HashSet<ProgressLevelNotification>();
        }
    
        public int ProjectMilestonesDocID { get; set; }
        public Nullable<int> ProjectMilestoneID { get; set; }
        public Nullable<int> DocStageID { get; set; }
        public Nullable<decimal> DocStagePercentage { get; set; }
        public Nullable<int> TaskTypeID { get; set; }
    
        public virtual ICollection<ProgressLevelNotification> ProgressLevelNotifications { get; set; }
    }
}
