//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMilestone
    {
        public ProjectMilestone()
        {
            this.MileStoneTaskTypes = new HashSet<MileStoneTaskType>();
        }
    
        public int ProjectMilestoneID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ProjectMilestone1 { get; set; }
        public string ProjectMilestoneDesc { get; set; }
        public Nullable<decimal> Weightage { get; set; }
        public string Type { get; set; }
        public string Remarks { get; set; }
        public string MileStone { get; set; }
        public Nullable<int> LOCK { get; set; }
        public Nullable<int> RequestID { get; set; }
        public string AutoDisplay { get; set; }
        public Nullable<int> ActivityTypeID { get; set; }
        public string SchedulingJS { get; set; }
        public string ProcurementHtmlDoc { get; set; }
    
        public virtual ICollection<MileStoneTaskType> MileStoneTaskTypes { get; set; }
        public virtual Project Project { get; set; }
    }
}
