//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStage
    {
        public int ProjectStageID { get; set; }
        public string StageName { get; set; }
        public string StageCode { get; set; }
        public string DistributationReq { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
