//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projectleveltask
    {
        public int ProjectleveltaskID { get; set; }
        public string DocumentDescription { get; set; }
        public string Completionon { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<System.DateTime> ActualStartdate { get; set; }
        public Nullable<System.DateTime> ActualEnd { get; set; }
        public Nullable<int> Dependency { get; set; }
        public Nullable<decimal> ProgressPercentage { get; set; }
        public string ActionType { get; set; }
    }
}
