//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectProgressLevelTemplate
    {
        public ProjectProgressLevelTemplate()
        {
            this.ProgressLevelTemplateDetails = new HashSet<ProgressLevelTemplateDetail>();
        }
    
        public int ProgressLevelTemplateID { get; set; }
        public string ProgressLevelTemplateName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ActivityTypeID { get; set; }
    
        public virtual ICollection<ProgressLevelTemplateDetail> ProgressLevelTemplateDetails { get; set; }
    }
}
