//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTaskList
    {
        public ProjectTaskList()
        {
            this.TaskDependencies = new HashSet<TaskDependency>();
            this.TaskDependencies1 = new HashSet<TaskDependency>();
            this.TaskHandoverDetails = new HashSet<TaskHandoverDetail>();
            this.TaskTransfers = new HashSet<TaskTransfer>();
            this.TimeSheetWeeklyDetails = new HashSet<TimeSheetWeeklyDetail>();
        }
    
        public int ProjectTaskID { get; set; }
        public int ProjectID { get; set; }
        public string TaskName { get; set; }
        public Nullable<int> TaskNo { get; set; }
        public Nullable<int> SubTaskNo { get; set; }
        public int DepatmentID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public decimal AllottedHours { get; set; }
        public int TaskTypeID { get; set; }
        public Nullable<int> Priority { get; set; }
        public int DesignationID { get; set; }
        public string PrerequisiteInformation { get; set; }
        public string Deliverables { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> TaskStatus { get; set; }
        public Nullable<int> TaskOwner { get; set; }
        public Nullable<decimal> TaskProgress { get; set; }
        public Nullable<int> ResourceRequestID { get; set; }
        public Nullable<int> ParentTaskID { get; set; }
        public Nullable<System.DateTime> AlertDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> LOCK { get; set; }
        public Nullable<int> FocalPoint { get; set; }
        public Nullable<int> ProgressSheetLock { get; set; }
        public Nullable<int> TaskOwnerTrf { get; set; }
        public Nullable<int> TaskObjectID { get; set; }
        public Nullable<System.DateTime> startApproveDate { get; set; }
        public Nullable<System.DateTime> endApproveDate { get; set; }
        public Nullable<System.DateTime> TaskcancelledDate { get; set; }
        public Nullable<int> startApproveUserID { get; set; }
        public Nullable<int> endApproveUserID { get; set; }
        public Nullable<int> ScopeChangeID { get; set; }
        public Nullable<int> ScopeChangeGroupFlag { get; set; }
        public string WBSID { get; set; }
        public Nullable<int> EstimationTaskID { get; set; }
        public Nullable<int> NormsID { get; set; }
        public string SysGen { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> NewActivityID { get; set; }
        public Nullable<int> DisplayOrderNo { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<decimal> TOTALHRS { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
        public string IsScheduled { get; set; }
        public string CurrentLockStatus { get; set; }
        public string ClientDeliverableNo { get; set; }
        public Nullable<bool> IsDeliverable { get; set; }
        public string DeliverableNo { get; set; }
        public Nullable<System.DateTime> StartDateOrg { get; set; }
        public Nullable<System.DateTime> EndDateOrg { get; set; }
        public string IsgroupTask { get; set; }
        public Nullable<int> GroupTaskID { get; set; }
        public Nullable<int> GroupTaskNo { get; set; }
        public Nullable<System.DateTime> ExpectedStartDate { get; set; }
        public Nullable<System.DateTime> ExpectedEndDate { get; set; }
        public Nullable<int> TaskDelay { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public string StartDelayAlertSent { get; set; }
        public string EndDelayAlertSent { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> CapUnitID { get; set; }
        public Nullable<int> QtyUnitID { get; set; }
        public string Capacity { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string IsImposed { get; set; }
        public Nullable<double> Number_1 { get; set; }
        public Nullable<double> Number_2 { get; set; }
        public Nullable<double> Number_3 { get; set; }
        public Nullable<double> Number_4 { get; set; }
        public Nullable<double> Number_5 { get; set; }
        public Nullable<double> Number_6 { get; set; }
        public Nullable<double> Number_7 { get; set; }
        public Nullable<double> Number_8 { get; set; }
        public Nullable<double> Number_9 { get; set; }
        public Nullable<double> Number_10 { get; set; }
        public Nullable<System.DateTime> DateTime_1 { get; set; }
        public Nullable<System.DateTime> DateTime_2 { get; set; }
        public Nullable<System.DateTime> DateTime_3 { get; set; }
        public Nullable<System.DateTime> DateTime_4 { get; set; }
        public Nullable<System.DateTime> DateTime_5 { get; set; }
        public Nullable<System.DateTime> DateTime_6 { get; set; }
        public Nullable<System.DateTime> DateTime_7 { get; set; }
        public Nullable<System.DateTime> DateTime_8 { get; set; }
        public Nullable<System.DateTime> DateTime_9 { get; set; }
        public Nullable<System.DateTime> DateTime_10 { get; set; }
        public string String_1 { get; set; }
        public string String_2 { get; set; }
        public string String_3 { get; set; }
        public string String_4 { get; set; }
        public string String_5 { get; set; }
        public string String_6 { get; set; }
        public string String_7 { get; set; }
        public string String_8 { get; set; }
        public string String_9 { get; set; }
        public string String_10 { get; set; }
        public Nullable<System.DateTime> ForeCastStartDate { get; set; }
        public Nullable<System.DateTime> ForeCastEndDate { get; set; }
        public Nullable<int> MasterTaskType { get; set; }
        public Nullable<decimal> TaskWeight { get; set; }
        public Nullable<decimal> TaskCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<int> forecastDuration { get; set; }
    
        public virtual ICollection<TaskDependency> TaskDependencies { get; set; }
        public virtual ICollection<TaskDependency> TaskDependencies1 { get; set; }
        public virtual ICollection<TaskHandoverDetail> TaskHandoverDetails { get; set; }
        public virtual ICollection<TaskTransfer> TaskTransfers { get; set; }
        public virtual ICollection<TimeSheetWeeklyDetail> TimeSheetWeeklyDetails { get; set; }
    }
}
