//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectContract
    {
        public int ProjectContractID { get; set; }
        public int ProjectID { get; set; }
        public string CopyName { get; set; }
        public int NormSetId { get; set; }
    }
}
