//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTempDocument
    {
        public int ProjectlDocumentsID { get; set; }
        public string Path { get; set; }
        public string FileExtention { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}
