//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedTask
    {
        public int RelatedTaskID { get; set; }
        public Nullable<int> TaskMilestoneBookedQtyID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string ApprovalStatus { get; set; }
    }
}
