//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemindMeProgressLevel
    {
        public int RemindMeProgressLevelID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> ProgressLevelID { get; set; }
        public Nullable<System.DateTime> PlannedDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> Remindar { get; set; }
    }
}
