//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceRequest
    {
        public int ResourceRequestID { get; set; }
        public int DepartmentID { get; set; }
        public int DesignationID { get; set; }
        public decimal AllottedManhours { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<int> NoOfResource { get; set; }
        public int ProjectID { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string ResourceRequestStatus { get; set; }
        public Nullable<int> RequestID { get; set; }
        public string SysGen { get; set; }
        public string IsEstimationRequest { get; set; }
        public Nullable<int> ResourceManagerID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Project Project { get; set; }
    }
}
