//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceAllocation
    {
        public int ResourceAllocationID { get; set; }
        public int ResourceRequestID { get; set; }
        public int UserID { get; set; }
        public string IsFocalPoint { get; set; }
        public Nullable<System.DateTime> allocatedFromDate { get; set; }
        public Nullable<System.DateTime> allocatedToDate { get; set; }
        public Nullable<decimal> AllocatedManHrs { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> DepartmentChange { get; set; }
    }
}
