//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleRight
    {
        public int RoleRightsID { get; set; }
        public int RoleID { get; set; }
        public short ModuleID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> EditAccess { get; set; }
        public Nullable<int> ViewAccess { get; set; }
        public Nullable<int> EditSilverAccess { get; set; }
        public Nullable<int> ViewSilverAccess { get; set; }
        public Nullable<int> EditGoldAccess { get; set; }
        public Nullable<int> ViewGoldAccess { get; set; }
        public Nullable<int> EditPlatinumAccess { get; set; }
        public Nullable<int> ViewPlatinumAccess { get; set; }
        public Nullable<int> EditFreeAccess { get; set; }
        public Nullable<int> ViewFreeAccess { get; set; }
        public Nullable<int> EditURMAccess { get; set; }
        public Nullable<int> ViewURMAccess { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
