//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleHealth
    {
        public int ScheduleHelthID { get; set; }
        public Nullable<decimal> GreenP { get; set; }
        public Nullable<decimal> YellowFromP { get; set; }
        public Nullable<decimal> YellowToP { get; set; }
        public Nullable<decimal> RedFromP { get; set; }
        public Nullable<decimal> RedToP { get; set; }
        public string ScheduleType { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModefiedBy { get; set; }
        public Nullable<System.DateTime> ModefiedOn { get; set; }
    }
}
