//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskTypeWiseProgress
    {
        public int TaskTypeWiseProgressID { get; set; }
        public Nullable<int> TaskTypeID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ProjectMilestoneID { get; set; }
        public Nullable<decimal> PercentWeitage { get; set; }
        public Nullable<System.DateTime> PlannedDate { get; set; }
        public Nullable<bool> TaskTypeChecked { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ProgressTrigger { get; set; }
    
        public virtual TaskType TaskType { get; set; }
    }
}
