//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskType
    {
        public TaskType()
        {
            this.MileStoneTaskTypes = new HashSet<MileStoneTaskType>();
            this.ProgressSheets = new HashSet<ProgressSheet>();
            this.TaskTypeWiseProgresses = new HashSet<TaskTypeWiseProgress>();
        }
    
        public int TaskTypeID { get; set; }
        public string TaskType1 { get; set; }
        public string TaskGroup { get; set; }
        public string TaskTypeCode { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ActivityType { get; set; }
        public string IsDefault { get; set; }
    
        public virtual ICollection<MileStoneTaskType> MileStoneTaskTypes { get; set; }
        public virtual ICollection<ProgressSheet> ProgressSheets { get; set; }
        public virtual ICollection<TaskTypeWiseProgress> TaskTypeWiseProgresses { get; set; }
    }
}
