//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskStartEndJustification
    {
        public int ID { get; set; }
        public int TaskID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ActualStartEndJustification { get; set; }
        public string isStart { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<int> AcceptanceClassID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    }
}
