//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskMilestoneBookedQty
    {
        public int TaskMilestoneBookedQtyID { get; set; }
        public int TaskID { get; set; }
        public int MileStoneID { get; set; }
        public int FileID { get; set; }
        public Nullable<int> NormsID { get; set; }
        public Nullable<int> DepatmentID { get; set; }
        public string TaskName { get; set; }
        public Nullable<int> TaskTypeID { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<decimal> AllottedHours { get; set; }
        public Nullable<int> WBSID { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Remarks { get; set; }
        public string DeliverableNo { get; set; }
        public Nullable<int> TaskOwner { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public Nullable<double> Number_1 { get; set; }
        public Nullable<double> Number_2 { get; set; }
        public Nullable<double> Number_3 { get; set; }
        public Nullable<double> Number_4 { get; set; }
        public Nullable<double> Number_5 { get; set; }
        public Nullable<double> Number_6 { get; set; }
        public Nullable<double> Number_7 { get; set; }
        public Nullable<double> Number_8 { get; set; }
        public Nullable<double> Number_9 { get; set; }
        public Nullable<double> Number_10 { get; set; }
        public Nullable<System.DateTime> DateTime_1 { get; set; }
        public Nullable<System.DateTime> DateTime_2 { get; set; }
        public Nullable<System.DateTime> DateTime_3 { get; set; }
        public Nullable<System.DateTime> DateTime_4 { get; set; }
        public Nullable<System.DateTime> DateTime_5 { get; set; }
        public Nullable<System.DateTime> DateTime_6 { get; set; }
        public Nullable<System.DateTime> DateTime_7 { get; set; }
        public Nullable<System.DateTime> DateTime_8 { get; set; }
        public Nullable<System.DateTime> DateTime_9 { get; set; }
        public Nullable<System.DateTime> DateTime_10 { get; set; }
        public string String_1 { get; set; }
        public string String_2 { get; set; }
        public string String_3 { get; set; }
        public string String_4 { get; set; }
        public string String_5 { get; set; }
        public string String_6 { get; set; }
        public string String_7 { get; set; }
        public string String_8 { get; set; }
        public string String_9 { get; set; }
        public string String_10 { get; set; }
        public Nullable<System.DateTime> ForeCastStartDate { get; set; }
        public Nullable<System.DateTime> ForeCastEndDate { get; set; }
        public Nullable<int> MasterTaskType { get; set; }
        public Nullable<decimal> TaskWeight { get; set; }
        public Nullable<decimal> TaskCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<int> ProcurementDocumentDataID { get; set; }
    }
}
