//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDetail_Contract
    {
        public int TaskDetailID { get; set; }
        public int ProjectTaskID { get; set; }
        public int EstimationTaskColumnID { get; set; }
        public string ColValue { get; set; }
        public Nullable<bool> IsTransfered { get; set; }
    }
}
