//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskCreationNormDetail
    {
        public int TaskCreationNormDetID { get; set; }
        public decimal CF { get; set; }
        public decimal RF { get; set; }
        public decimal DMF { get; set; }
        public int Quantity { get; set; }
        public int ProjectTaskID { get; set; }
    }
}
