//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskTransfer
    {
        public int TaskTransferID { get; set; }
        public int TaskID { get; set; }
        public System.DateTime TransferDate { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int ToUser { get; set; }
        public int FromUser { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
    
        public virtual ProjectTaskList ProjectTaskList { get; set; }
    }
}
