//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDesignation
    {
        public int TaskDesignationID { get; set; }
        public int DesignationID { get; set; }
        public decimal Hours { get; set; }
        public int ProjectTaskID { get; set; }
        public Nullable<int> EstimationTaskID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> ProjectStageID { get; set; }
        public Nullable<int> NormID { get; set; }
        public Nullable<int> RequestID { get; set; }
    }
}
