//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskListColorCell
    {
        public int ProjectTaskColorCellID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ProjectTaskID { get; set; }
        public string DataMappingID { get; set; }
        public string BackgroudColorCode { get; set; }
        public string FontColorCode { get; set; }
    }
}
