//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskMilestoneBookedQtyFile
    {
        public int TaskMilestoneBookedQtyFileID { get; set; }
        public Nullable<int> TaskMilestoneBookedQtyID { get; set; }
        public Nullable<int> UploadDeliverableFileID { get; set; }
    }
}
