//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDependency_Contract
    {
        public int TaskDependencyID { get; set; }
        public int TaskID { get; set; }
        public int DependencyTaskID { get; set; }
        public int DependencyType { get; set; }
        public int LagDay { get; set; }
    }
}
