//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxCode
    {
        public int Taxcodeid { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<int> Createby { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
