//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheetWeekly
    {
        public TimeSheetWeekly()
        {
            this.TimeSheetDeviations = new HashSet<TimeSheetDeviation>();
            this.TimeSheetWeeklyDetails = new HashSet<TimeSheetWeeklyDetail>();
            this.TimeSheetRejections = new HashSet<TimeSheetRejection>();
        }
    
        public int TimeSheetWeeklyID { get; set; }
        public Nullable<System.DateTime> TimeSheetFromDate { get; set; }
        public Nullable<System.DateTime> TimeSheetToDate { get; set; }
        public Nullable<int> TimeSheetStatus { get; set; }
        public string Remark { get; set; }
        public Nullable<int> FinalStatus { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
    
        public virtual ICollection<TimeSheetDeviation> TimeSheetDeviations { get; set; }
        public virtual ICollection<TimeSheetWeeklyDetail> TimeSheetWeeklyDetails { get; set; }
        public virtual ICollection<TimeSheetRejection> TimeSheetRejections { get; set; }
    }
}
