//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransmittalDelList
    {
        public int DelTransmittalId { get; set; }
        public int DeliverableId { get; set; }
        public Nullable<int> MilestoneId { get; set; }
        public Nullable<int> RevisionId { get; set; }
        public int FileId { get; set; }
        public int TransmittalId { get; set; }
    }
}
