//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transmittal
    {
        public int TransmittalId { get; set; }
        public string TransmittalTitle { get; set; }
        public int ProjectId { get; set; }
        public string TransmittalNo { get; set; }
        public string Remarks { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
        public int TransmitalTemplateID { get; set; }
    
        public virtual User User { get; set; }
    }
}
