//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnlockTimeSheetDeviation
    {
        public int UnlockTimeSheetDeviationID { get; set; }
        public int TimeSheetDeviationID { get; set; }
        public Nullable<int> TimeSheetWeeklyID { get; set; }
        public string Deviation { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> JustifydeviationHrs { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> AcceptanceClassID { get; set; }
        public string AcceptanceRemark { get; set; }
        public Nullable<bool> IsNewActivity { get; set; }
        public int UnlockTimeSheetWeeklyID { get; set; }
    }
}
