//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTechnology
    {
        public int UserTechnologyID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TechnologyID { get; set; }
        public string Level { get; set; }
        public Nullable<decimal> NoOFYears { get; set; }
    }
}
