//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEmployeeProject
    {
        public int UserEmployeeProjectID { get; set; }
        public string ProjectName { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserEmployerHistoryID { get; set; }
    }
}
