//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    
    public partial class usp_ProjectWiseCostReport_Result1
    
    {
        public int id { get; set; }
        public string DepartmentName { get; set; }
        public decimal PV { get; set; }
        public decimal EV { get; set; }
        public decimal CVDoller { get; set; }
        public decimal CVPercent { get; set; }
        public decimal SVDoller { get; set; }
        public decimal SVPercent { get; set; }
        public decimal CPI { get; set; }
        public decimal SPI { get; set; }
        public decimal AC { get; set; }
    }
}
