//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CONFIGFILE
    {
        public int ConfigID { get; set; }
        public string SmtpClientHost { get; set; }
        public string StrongPwReqd { get; set; }
        public decimal NoofAttemptsforPassword { get; set; }
        public decimal PwChangeAfterNoOfDays { get; set; }
        public string PwChangeHistoryReqd { get; set; }
        public string UserIDExpiryField { get; set; }
        public decimal DormantNoofDays { get; set; }
        public decimal SessionTimeOutInMin { get; set; }
        public Nullable<int> ScrollTextDelay { get; set; }
        public string SiteAdminUserCode { get; set; }
        public decimal NoOfTimesRepeatPW { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string UserCode { get; set; }
        public string SiteAdminUserName { get; set; }
        public string AdminEmailID { get; set; }
        public string SMTPUserid { get; set; }
        public string SMTPPassword { get; set; }
        public Nullable<decimal> ShowLastNNoofWebOrders { get; set; }
        public string ChangeRequestEmailAddress { get; set; }
        public string NewClientInquiryEmailAddress { get; set; }
        public string FeedbackEmailAddress { get; set; }
        public Nullable<decimal> SSLEnabled { get; set; }
        public string TechnicalEmailAddress { get; set; }
        public decimal PwChangeReminderDays { get; set; }
    }
}
