//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBSTemplateDetail
    {
        public int WBSTemplateDetailId { get; set; }
        public int WBSTemplateID { get; set; }
        public int WBSID { get; set; }
        public string WBSName { get; set; }
        public string WBSCode { get; set; }
        public string ParentWBSName { get; set; }
        public string ParentWBSCode { get; set; }
        public Nullable<int> ParentWBSID { get; set; }
    
        public virtual WBSTemplate WBSTemplate { get; set; }
    }
}
