//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBSTemplate
    {
        public WBSTemplate()
        {
            this.WBSTemplateDetails = new HashSet<WBSTemplateDetail>();
        }
    
        public int WBSTemplateID { get; set; }
        public string WBSTemplateName { get; set; }
        public int createdBy { get; set; }
        public System.DateTime createdOn { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual ICollection<WBSTemplateDetail> WBSTemplateDetails { get; set; }
    }
}
