//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyTaskList
    {
        public int WeeklyTaskListID { get; set; }
        public int TaskID { get; set; }
        public int UserID { get; set; }
        public System.DateTime WeekStartDate { get; set; }
        public System.DateTime WeekEndDate { get; set; }
    }
}
